### ISSUE TITLE
Code generator not working

### ISSUE THREAD

**Issue by RvRooijen** [sschmid/Entitas-Standalone#1]
The code generator does not work with the last version. There are also a lot of components in the generated folder that are not in the EntitasPure folder.

**Comment by sschmid** [comment]
Hi, just updated to Entitas 0.42.0. Eveything should work now. I also added `generate.sh` which you can run like this `./generate.sh`. This should simplify the process. Happy to accept PR for Windows script if needed.

General note about the current code generator CLI:
- Entitas.properties has to be in the same folder as the MyProject.csproj file
- You have to cd into the folder where the Entitas.properties is located when running the code generator

But as I said, you can also just run `./generate.sh` instead.

Let me know if it works for you now

**Comment by sschmid** [comment]
Sorry for the late reply, I just saw I'm not getting any notifications for this project, just changed that now.

**Comment by distantcam** [comment]
Not sure if this is the original problem, but I'm having an issue running the generator on a windows machine with .NET 4.0 installed.

The problem is the CLI is running under .NET 4.0, so the 4.0 mscorlib is loaded. Then the plugins are loaded but because they're .NET 2.0 assemblies the assembly resolver tries to to load the 2.0 mscorlib and fails.

```
AppDomain load: Entitas.CodeGeneration.Plugins
  - Loading: Entitas.CodeGeneration.Plugins
    - Resolved: ..\Entitas\CodeGenerator\Plugins\Default\Entitas.CodeGeneration.Plugins.dll
System.IO.FileLoadException: Could not load file or assembly 'Entitas.CodeGeneration.Plugins' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'Entitas.CodeGeneration.Plugins' ---> System.IO.FileLoadException: Could not load file or assembly 'file:///D:\src\unity\EntitasPure\Entitas\CodeGenerator\Plugins\Default\Entitas.CodeGeneration.Plugins.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///D:\src\unity\EntitasPure\Entitas\CodeGenerator\Plugins\Default\Entitas.CodeGeneration.Plugins.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Entitas.CodeGeneration.CodeGenerator.AssemblyResolver.onAssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)


   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.AppDomain.Load(String assemblyString)
   at Entitas.CodeGeneration.CodeGenerator.AssemblyResolver.Load(String path)
   at Entitas.CodeGeneration.CodeGenerator.CodeGeneratorUtil.LoadTypesFromPlugins(Properties properties)
   at Entitas.CodeGeneration.CodeGenerator.CodeGeneratorUtil.CodeGeneratorFromProperties()
   at Entitas.CodeGeneration.CodeGenerator.CLI.Generate.Run(String[] args)
   at Entitas.CodeGeneration.CodeGenerator.CLI.MainClass.Main(String[] args)
```

EDIT: Yep, just recompiled Entitas.CodeGeneration.CodeGenerator.CLI to .NET 3.5 and that fixed the issue for me.

**Comment by sschmid** [comment]
I recreated this project from scratch using Entitas 1.14 and force pushed.
See readme for code generation instructions
